# Generated by Django 5.0.1 on 2024-02-04 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
